export const FRAMEWORKS = [
  // Original List
  "Coherent Rhetorical Escalation",
  "Analogical reasoning",
  "Analytical control point",
  "Anomysem",
  "Atomic issue identification",
  "Backwards reach",
  "Bayesian inference",
  "Binary fork",
  "Build firewall nodes between paths",
  "Causal spine",
  "Centrality matrix",
  "Closest to the root with highest degree of centrality",
  "Common overlap zones",
  "Conceptual mapping (cross-domain analogy)",
  "Connect to divergent bridge",
  "Core element analysis",
  "Cross-impact matrix",
  "Synthetic matrix",
  "Deductive reasoning",
  "Dimensional Reduction (Petri net)",
  "Dimensional Reduction (PCA + SVD)",
  "Feedback loop origin point",
  "Fractal analysis",
  "First principles",
  "Formal logic mapping",
  "Fractal pattern",
  "Hybrid analog logic",
  "Historical-cause comparison",
  "Info-theoretic centrality",
  "Interdisciplinary synthesis",
  "Invariance detection (symmetry)",
  "Analogy tensor mapping framework",
  "Topological data",
  "Isomorphic mapping",
  "Logic architecture",
  "Logical sequences",
  "MECE",
  "Monte Carlo dispersion",
  "Morphological ladder mapping",
  "Morph synthesis",
  "Network-based analysis",
  "Node with highest dispersion",
  
  // Set 2 (100 Frameworks)
  "Counterfactual chain analysis",
  "Minimal sufficient cause sets",
  "Constraint propagation grid",
  "Axiom–lemma–theorem ladder",
  "Consistency constraint matrix",
  "Necessity–sufficiency lattice",
  "Failure path decomposition",
  "Contradiction exposure map",
  "Premise dependency graph",
  "Logic-layer stack tracing",
  "Argument topology mapping",
  "Rule-space exploration tree",
  "Error-source triangulation",
  "Hypothesis falsification gauntlet",
  "Inference pressure test",
  "Multi-layer network lens",
  "Flow bottleneck centrality",
  "Edge stress testing",
  "Dynamic path sensitivity map",
  "Influence propagation model",
  "Feedback loop cartography",
  "Cascade failure simulation",
  "Bridge-node vulnerability scan",
  "Modularity and community partitioning",
  "Path redundancy design",
  "Structural hole detection",
  "K-core stability analysis",
  "Minimum cut / maximum flow framing",
  "Network motif detection",
  "Multi-hop impact gradient",
  "Bayesian causal graph refinement",
  "Uncertainty funneling",
  "Scenario entropy scan",
  "Sensitivity tornado mapping",
  "Probabilistic fault tree",
  "Risk surface mapping",
  "Distributional tail probing",
  "Regime-switch detection",
  "Hidden variable hypothesis hunt",
  "Confidence-weighted evidence grid",
  "Manifold unfolding analysis",
  "Principal conflict components",
  "Constraint subspace isolation",
  "Eigenvector influence profiling",
  "Feature sparsity pruning",
  "Orthogonal factor lattice",
  "Latent driver extraction",
  "Similarity manifold clustering",
  "Signal–noise separation stack",
  "Trade-off frontier (Pareto lens)",
  "Cross-domain invariance hunt",
  "Structural analogy lattice",
  "Tensorized comparison grid",
  "Multi-axis metaphor cube",
  "Isomorphic process pairing",
  "Role-structure remapping",
  "Mechanism-level analogy chains",
  "Failure-analogy cataloging",
  "Cross-context pattern overlay",
  "Analogy-driven hypothesis transfer",
  "Morphological conflict grid",
  "Option recombination engine",
  "Constraint-compatible morph cube",
  "Design space tiling",
  "Boundary condition morphing",
  "Discrete state recomposition",
  "Switch-point catalog",
  "Interface variant mapping",
  "Constraint–choice incidence matrix",
  "Configuration dominance scan",
  "State-transition fingerprinting",
  "Phase-change locator",
  "Temporal anomaly alignment",
  "Leading-indicator sieve",
  "Lag-chain decomposition",
  "Time-scale separation map",
  "Shock-response signature map",
  "Path-dependent history replay",
  "Drift and rupture detection",
  "Critical slowing-down scan",
  "Information bottleneck locator",
  "Mutual information lattice",
  "Redundancy and loss map",
  "Signaling pathway analysis",
  "Codebook mismatch finder",
  "Compression-clarity curve",
  "Surprise hotspot detection",
  "Entropy budget allocation",
  "Information-flow Petri net",
  "Noise-robust core extraction",
  "Multi-model consensus grid",
  "Perspective superposition map",
  "Cross-framework intersection finder",
  "Meta-MECE partitioning",
  "Conflict-resolution synthesis tree",
  "Core–periphery synthesis ring",
  "Multi-criteria decision surface",
  "Robustness–fragility spectrum",
  "Failure-mode coverage checker",
  "Root-cause convergence radar",

  // Set 3 (100 New Frameworks)
  "Critical Junction Mapping",
  "Dominant Mechanism Isolation",
  "Causal Density Indexing",
  "Dependence Chain Compression",
  "Failure Root Skeletonization",
  "Constraint Spine Extraction",
  "Logical Boundary Modeling",
  "State-Space Collapse Method",
  "Invariant Surface Analysis",
  "Constraint-Tension Mapping",
  "Hidden Premise Extraction",
  "Causal Tunnel Identification",
  "Symmetry-Break Locator",
  "Multi-Frame Causal Overlay",
  "Cross-Layer Logic Linking",
  "Variable Dominance Analysis",
  "Structural Divergence Check",
  "Mechanism Consistency Matrix",
  "Trigger-to-Consequence Mapping",
  "Threshold Condition Finder",
  "Sparse Causal Graphing",
  "Nonlinear Junction Scan",
  "Central Switch-Point Detection",
  "Constraint Network Pruning",
  "Redundancy Collapse Scan",
  "Event Horizon Mapping",
  "Convergence Basin Detection",
  "Signal Deformation Tracer",
  "Flow-Resistor Identification",
  "Isolation-Impact Ratio Analysis",
  "Inconsistency Stress Mapping",
  "Hierarchy-to-Network Conversion",
  "Multi-Logic Fusion Grid",
  "Cross-Scale Causal Folding",
  "Robust Node Identification",
  "Logical Fracture Identification",
  "Causal Direction Entropy Scan",
  "Temporal Convergence Clustering",
  "Root-Tunnel Extraction",
  "Causal Irradiation Mapping",
  "Multi-Cause Overlay Stack",
  "Graph Entanglement Measurement",
  "Structural Skeleton Map",
  "Multi-Resolution Logic Pass",
  "Path Collapse Prioritization",
  "Constraint Friction Analysis",
  "Virtuous/Vicious Loop Symmetry Scan",
  "Leverage Gradient Analyzer",
  "Node Rigidity Measurement",
  "Dominance Arc Tracing",
  "Structural Pivot Detection",
  "Causal Delta Mapping",
  "Mechanism Purification Test",
  "Non-Redundant Core Extraction",
  "Cross-Scenario Convergence Scan",
  "Antagonistic Variable Pairing",
  "Causal Knot Detection",
  "Flow Perturbation Mapping",
  "Junction Triage Method",
  "Divergent Mechanism Sorting",
  "Temporal Critical Pathing",
  "Minimal Intervention Modeling",
  "Sensitivity Lattice Building",
  "Transition Shard Detection",
  "Multi-Step Causal Weighting",
  "Impact Radius Ranking",
  "Constraint Activation Mapping",
  "Equilibrium Shift Locator",
  "Network Rigidity Index",
  "Predictive Drift Map",
  "Signal Coherence Tracing",
  "Dominance Chain Extraction",
  "Cross-Model Structural Alignment",
  "Root Corridor Identification",
  "Node Influence Absorption Test",
  "Constraint Collapse Mapping",
  "Phase Shift Indicator Matrix",
  "Hidden Frequency Patterning",
  "Causal Drift Detector",
  "Mechanism Lateral Transfer Method",
  "Causal Geometry Projection",
  "Logical Graph Reversal",
  "Influence Synapse Mapping",
  "Structural Latency Detection",
  "Signal Origin Reconstruction",
  "Cross-Temporal Symmetry Scan",
  "Logic-Density Compression",
  "Core-Mechanism Resonance Scan",
  "Layered Mechanism Distillation",
  "Flow-Harmonic Analysis",
  "System Strain Detector",
  "Causal Aperture Mapping",
  "Multi-Constraint Intersection Finder",
  "State Divergence Heatmap",
  "Root-Mechanism Purity Test",
  "Causal Velocity Mapping",
  "Structural Dissonance Finder",
  "Information Path Distortion Scan",
  "Cross-Condition Robustness Test",
  "Hidden Structure Excavation",

  // Set 4 (100 New Frameworks)
  "Dominant Transition Locator",
  "Causal Compression Layering",
  "Interference Pattern Mapping",
  "Stability Basin Identification",
  "Noise-Resistant Structure Extraction",
  "Critical Assumption Dissection",
  "Pathway Tension Analysis",
  "Multi-Causal Superposition Grid",
  "Logic Gate Cascade Mapping",
  "Contradiction Flow Mapping",
  "Hierarchical Collapse Finder",
  "Root Mechanism Constriction Test",
  "Causal Plane Intersection",
  "Variable Polarization Mapping",
  "Cross-Motive Mechanism Detection",
  "Causal Angular Deviation Scan",
  "Structural Immunity Test",
  "Causal Circuit Reconstruction",
  "Edge-Based Causal Ranking",
  "Constraint Warping Analysis",
  "Transformational Pivot Scan",
  "Logical Skeleton Compression",
  "Interference Node Detection",
  "Feedback Geometry Mapping",
  "Multi-Variable Dependency Mesh",
  "Pattern Fracture Detection",
  "Complexity Collapse Estimator",
  "Influence Radius Mesh Mapping",
  "Premise Layer Decomposition",
  "Cross-Domain Mechanism Folding",
  "Signal Mutation Tracker",
  "Node Entropy Stability Scan",
  "Transition Stress Tensor",
  "Info-Flow Equilibrium Detector",
  "Meta-Causal Interaction Grid",
  "Structural Drift Map",
  "Logic Constraint Folding",
  "Nonlinear Trigger Mapping",
  "Causal Parallax Detection",
  "Cross-Structure Alignment Matrix",
  "Convergence Line Extraction",
  "Causal Attenuation Mapping",
  "Node Attrition Model",
  "Sparse Trigger Identification",
  "Fractal Trigger Patterning",
  "Multi-Frame Reduction Overlay",
  "Mechanism Purity Distiller",
  "Interference Field Overlay",
  "Correlation–Causation Separator",
  "Hypergraph Influence Extraction",
  "Constraint Flux Mapping",
  "Cross-Layer Drift Detector",
  "Synthetic Causal Weave",
  "Mechanism Resonance Finder",
  "Causal Torque Analysis",
  "State-Shift Tension Mapping",
  "Trigger Density Matrix",
  "Boundary Distortion Tracking",
  "Logic-Cycle Deconstruction",
  "Emergent Pattern Isolation",
  "Convergence Funnel Construction",
  "Causal Relevance Lattice",
  "System Rigidity Estimator",
  "Energy-Path Efficiency Mapping",
  "Causal Overconstraint Detector",
  "Transition Heat Signature Scan",
  "Mechanism Divergence Mapping",
  "Temporal Stress Lattice",
  "Causal Diffusion Network",
  "Phase-Transition Locus Finder",
  "Flow Disruption Cartography",
  "Constraint Geometry Mapping",
  "Root-Lineage Reconstruction",
  "Condition Trigger Sequencer",
  "Density-Based Mechanism Filtering",
  "Causal Field Partitioning",
  "Dominant Arc Extraction",
  "Logic Substructure Mining",
  "Sparsity-Weighted Causal Ranking",
  "Boundary Violation Mapping",
  "Combinatorial Causal Folding",
  "Temporal Inversion Test",
  "Transition Gap Detection",
  "Mechanism Alignment Tensor",
  "Core Divergence Filter",
  "Causal Depth Estimator",
  "Transition Granularity Scan",
  "Causal Bridge Reconstruction",
  "State-Space Friction Index",
  "Mechanism Surface Mapping",
  "Meta-Structural Convergence Check",
  "Causal Obstruction Matrix",
  "Cross-Mechanism Resonance Overlay",
  "Phase Instability Detector",
  "Root Consistency Corridor",
  "Interference Tension Weave",
  "Signal-to-Structure Contrast Mapping",
  "Constraint Failure Spectrum",
  "Structural Saturation Detector",
  "Mechanism Compression Gradient",

  // Set 5 (100 New Frameworks)
  "Constraint Relaxation Engine",
  "Variable-Space Expansion",
  "Delta-State Comparison",
  "Precursor Event Mapping",
  "Threshold Breach Analysis",
  "Fault Cascade Localization",
  "System Rigidity Scan",
  "Temporal Drift Mapping",
  "Node Sensitivity Gradient",
  "Multi-Order Dependency Ladder",
  "Combinatorial State Pruning",
  "Logic Field Superposition",
  "Rate-Limit Inference Model",
  "Nonlinear Disturbance Tracking",
  "Perturbation Signature Matching",
  "State-Dominance Hierarchy",
  "Axial Problem Rotation",
  "Parametric Collapse Analysis",
  "Core Signal Isolation",
  "Reliability Envelope Mapping",
  "Compression-to-Core Ratio Check",
  "Information Asymmetry Detector",
  "Entropy Increase Locator",
  "Unstable Attractor Detection",
  "Discontinuity Pattern Finder",
  "Structural Leak Finder",
  "Implicit Premise Scanner",
  "Causal Frame Realignment",
  "Interference Pattern Detector",
  "Minimal Explanation Set Search",
  "Failure Mode Overlay",
  "Logic Topography Mapping",
  "Trigger-Chain Reversal",
  "State Renewal Simulation",
  "Symmetry-Break Detection",
  "Emergent Condition Finder",
  "Competing Hypothesis Tournament",
  "Accelerated Decomposition Engine",
  "Convergence Basin Mapping",
  "Dominant Flow Path Analysis",
  "Latent Interaction Probe",
  "Stability Margin Calculator",
  "Signal-to-Noise Inversion",
  "Discrete Jump Locator",
  "Non-Obvious Constraint Extraction",
  "High-Impact Low-Visibility Filter",
  "Triangulated Logic Pinning",
  "Conflict-Free Reduction",
  "Reverse Construction Blueprinting",
  "Input-Distortion Mapping",
  "Spring-Back Failure Test",
  "Multi-Scale Overlay Grid",
  "Coherence Rupture Finder",
  "Null Hypothesis Stability Test",
  "Minimal-Resistance Path Scan",
  "Bifurcation Trigger Search",
  "Dynamic Range Shrink Test",
  "Root-Reachability Index",
  "Governing Variable Selector",
  "Intermittent Fault Skeleton",
  "Elastic Boundary Test",
  "Distorted Equilibrium Finder",
  "Universal Constraint Inventory",
  "Assumption Distance Meter",
  "Causal Density Compression",
  "Order-of-Operations Sensitivity",
  "Directional Causality Scan",
  "Preloading Condition Detector",
  "Phase Transition Locator",
  "Error Amplification Ladder",
  "Root Collapse Reconstruction",
  "Reduction-to-Mechanism Test",
  "Rule-Density Conflict Check",
  "Invisible Bottleneck Finder",
  "Tolerance Exceedance Scan",
  "Core Mechanism Hypothesis Net",
  "Imbalance Mapping Grid",
  "Friction Point Estimator",
  "Target-State Feasibility Test",
  "Reversion-to-Failure Map",
  "Paradox Resolution Matrix",
  "Double-Blind Logic Check",
  "Variable Clamping Strategy",
  "Interference Overlay Model",
  "Blind Spot Geometry Scan",
  "Temporal Compaction Test",
  "Boundary Condition Reversal",
  "Initial Condition Reconstruction",
  "Peak-Stress Node Identification",
  "Topological Fault Reconstruction",
  "Activation-Energy Approximation",
  "System Flow Re-Segmentation",
  "Dominant Constraint Enumeration",
  "Reverse-Stability Analysis",
  "Interaction-Pair Stress Test",
  "Pre-Failure Signature Extraction",
  "Causal Knot Detangler",
  "Logic Anchoring Grid",
  "Emergent Failure Confluence Map",
  "Terminal Constraint Detection",

  // Set 6 (100 New Frameworks)
  "Root-State Lattice Mapping",
  "Minimal Energy Path Analysis",
  "Consequence Backflow Tracing",
  "Signal-to-Noise Priority Filter",
  "Constraint Collapse Method",
  "Variable Dominance Mapping",
  "Zero-Redundancy Decomposition",
  "Temporal Compression Grid",
  "Cross-Domain Invariant Extraction",
  "Trigger-Point Isolation Framework",
  "Ultra-Sparse Causal Graphs",
  "Error-Propagation Skeletonizing",
  "Dominant Trajectory Finder",
  "State-Shift Boundary Detection",
  "Systemic Range Reduction",
  "Failure Kernel Analysis",
  "Latent Mechanism Excavation",
  "Degeneracy Removal Protocol",
  "Bottleneck Elasticity Test",
  "Interference Pattern Reasoning",
  "Parallel Failure Mode Divergence",
  "Structural Pressure Mapping",
  "Root-Zone Gradient Locator",
  "Interface Discontinuity Detection",
  "Constraint Entanglement Separator",
  "Sequential Purification Method",
  "Critical Vector Isolation",
  "Causal Density Reduction Pass",
  "Meta-Boundary Testing",
  "Phase-Shift Threshold Mapping",
  "Computational Depth Scan",
  "Multi-Layer Parity Checker",
  "Overlapping Gradient Resolver",
  "Focal-Point Inversion Logic",
  "Dimensional Stress Discovery",
  "System-Limit Probing Model",
  "Topology-Driven Search Method",
  "Cumulative Friction Analyzer",
  "Key-Transition Compression",
  "Causal Inflection Scan",
  "Pressure-Node Prioritization",
  "Feedback-Decay Tracking",
  "Intermittent Fault Miner",
  "Multi-Factor Gradient Stack",
  "Fractal Root Reconstruction",
  "Behavioral Convergence Check",
  "Structural Irreversibility Detector",
  "Compression-First Deduction",
  "Multi-Frame Overlay Reasoning",
  "Non-Linear Tension Grid",
  "Info-Entropy Funnel",
  "Leverage-Point Delta Scan",
  "Boundary Stress Simulation",
  "Cross-Probability Merge Logic",
  "Fractal Divergence Test",
  "Recurrent Evidence Consolidation",
  "Cascade Frame Reconstruction",
  "Single-Cause Probability Distiller",
  "State-Collapse Sequencing",
  "Inverse-Density Mapping",
  "Critical Chain Surface Method",
  "Systemic Drift Detection",
  "Multi-Range Compression Cubes",
  "Gradient-Peak Locator",
  "Recursive Limitation Peeling",
  "Conflict Zone Reduction",
  "Dominant-Cause Extraction Beam",
  "Complexity Gradient Reversal",
  "Density-Driven Prioritizing",
  "Variance Corridor Compression",
  "Failure Front Projection",
  "Causal Volume Reduction",
  "System-Weight Redistribution",
  "Critical Flow Separation",
  "Limit-Approach Pattern Scan",
  "Step-Before-Break Detection",
  "Constraint Collapse Cascade",
  "Rare-Event Path Modeling",
  "Convergent Evidence Axis",
  "Peak-Influence Mapping",
  "Curvature-Based Diagnostic",
  "Iterative Sharp-Point Finding",
  "Multi-Cause Density Slicer",
  "Fracture-Point Projection",
  "Principal Deformation Detection",
  "Inverted Proof Search",
  "State-Density Clustering",
  "Root-Magnet Heuristic",
  "Transition Frost-Line Method",
  "Constraint-Sculpting Logic",
  "Meta-Reduction Protocol",
  "Error-Cluster Segmentation",
  "Deterministic Core Mining",
  "Structure-First Reduction Method",
  "Fractal Compression Ladder",
  "Causal Sparsification Sweep",
  "Critical-Node Probability Weighing",
  "Inverse Cascade Mapping",
  "Root-Cause Envelope Finder",
  "Cross-Dimensional Causal Fusion",

  // Set 7 (200 New Frameworks)
  "Adaptive Resolution Matrix",
  "Anchored Variable Elimination",
  "Anticipatory Constraint Mapping",
  "Asymmetry Stress Test",
  "Attraction–Repulsion Logic Grid",
  "Backward Horizon Collapse",
  "Baseline Drift Detector",
  "Behavioral Signal Isolation",
  "Boundary Fracture Scan",
  "Boundary Softening Strategy",
  "Branch-Collapse Ladder",
  "Breakpoint Cross-Section Map",
  "Cascade Origin Detector",
  "Cascade Velocity Model",
  "Causal Resistance Score",
  "Central Bottleneck Tensor",
  "Channel Narrowing Analysis",
  "Chronological Failure Slice",
  "Cluster-to-Signal Ratio Method",
  "Coherence Gap Extractor",
  "Competing Hypotheses Grid",
  "Complexity Compression Engine",
  "Compression-Before-Inference Rule",
  "Conditional Tipping Matrix",
  "Conduction Path Finder",
  "Conflict-Free Reformulation",
  "Constraint Horizon Mapping",
  "Constraint Reversal Strategy",
  "Convergence Pressure Gauge",
  "Convergence-Divergence Index",
  "Critical Aperture Detection",
  "Critical Drift Locator",
  "Cross-State Mutation Model",
  "Cross-System Density Analysis",
  "Cross-Trajectory Intersectioning",
  "Data Scarcity Compensation",
  "Decision Aperture Method",
  "Decision Tree Reversal",
  "Degradation Curve Extraction",
  "Delta-State Differentiation",
  "Demand-Signal Stress Mapping",
  "Density-of-Logic Check",
  "Dependency Break Scan",
  "Dependency Gravity Index",
  "Differential Misalignment Test",
  "Disruption Anticipation Ladder",
  "Disruption-to-Stability Ratio",
  "Divergent-Path Likelihood Test",
  "Drift-to-Deviation Model",
  "Dynamic Boundary Redraw",
  "Dynamic Inference Filter",
  "Edge-Instability Detector",
  "Elastic Constraint Reduction",
  "Emergence Potential Scan",
  "Energy-to-Error Ratio",
  "Entropy-Gradient Pathfinding",
  "Equilibrium Shift Prediction",
  "Error Gravity Mapping",
  "Escape-Route Analysis",
  "Expectation–Outcome Tension Map",
  "Failure Load Distribution",
  "Fault-Line Detection Web",
  "Feedback Strength Index",
  "Fracture-Before-Break Model",
  "Friction-Point Density Check",
  "Function Drift Detection",
  "Futures Backflow Test",
  "Gap-Convergence Ratio",
  "Gap-Induced Divergence Mapping",
  "Gatekeeping Variable Identification",
  "Hidden Burden Analysis",
  "Hidden Coupling Detector",
  "Hidden Momentum Scan",
  "High-Impact Factor Isolation",
  "Horizon Collapse Reconstruction",
  "Hybrid Influence Grid",
  "Ignition-Point Analysis",
  "Imbalanced Weight Pull Scan",
  "Inertia Reduction Strategy",
  "Influence Symmetry Test",
  "Information-to-Noise Compression",
  "Initial Condition Inflation Test",
  "Input-Error Translation Scan",
  "Instability Gradient Mapping",
  "Interference-Pattern Analysis",
  "Interlocking Constraint Filter",
  "Internal Tension Mapping",
  "Inverse Dependency Simulation",
  "Inverse Loading Model",
  "Irreversibility Check",
  "Junction-Point Identification",
  "Key-Variable Substitution Method",
  "Kinetic Error Amplification Test",
  "Latent Accumulation Detector",
  "Latent Influence Matrix",
  "Leverage-Ratio Mapping",
  "Limiting Factor Collapse",
  "Local-to-Global Error Projection",
  "Logical Drift Correction",
  "Logical Pressure Zones",
  "Loop Integrity Scan",
  "Loss-of-Signal Reconstruction",
  "Map-Contraction Method",
  "Masked Constraint Detector",
  "Minimal Intervention Search",
  "Misalignment Gradient Map",
  "Misplaced Priority Dissection",
  "Momentum-Breakpoint Ladder",
  "Multi-Layer Cross-Checking",
  "Multi-Path Resistance Scan",
  "Mutation-to-Outcome Ladder",
  "Narrow-Gate Analysis",
  "Network Strain Mapping",
  "Neutral Zone Identification",
  "Noise-to-Decision Filter",
  "Nonlinear Drift Detection",
  "Off-Axis Influence Scan",
  "Off-Path Energy Dissipation",
  "Opposing Force Identification",
  "Order-Reversal Simulation",
  "Overload-to-Failure Ratio",
  "Overshoot Prediction Grid",
  "Path-Friction Modeling",
  "Path-Reduction Strategy",
  "Pattern-Break Isolation",
  "Pattern-Inversion Method",
  "Peak-Strain Detector",
  "Phase-Shift Impact Scan",
  "Pressure-Point Collapse Test",
  "Priority Drift Map",
  "Probabilistic Causation Map",
  "Process-Stability Indicator",
  "Progressive Misalignment Forecast",
  "Propagation-Delay Mapping",
  "Proximity-Pressure Method",
  "Rate-of-Change Signal Test",
  "Recursive Constraint Cutting",
  "Reduction-to-Mechanism Test",
  "Redundant Variance Removal",
  "Reference-Point Shifting",
  "Resistance-to-Change Index",
  "Reverse Tension Mapping",
  "Reversion Pressure Model",
  "Risk Load Decomposition",
  "Root-Signal Strength Check",
  "Scaling-Failure Prediction",
  "Self-Tension Analysis",
  "Sensitivity-Funneling Method",
  "Sequence-Break Detector",
  "Signal-Degradation Ladder",
  "Signal Purification Pipeline",
  "Single-Cause Verification Test",
  "Slip-Point Detection",
  "Snapshot-State Compression",
  "Stability Envelope Mapping",
  "Stability-to-Chaos Ratio",
  "State-Density Analysis",
  "State-Mutation Probability Field",
  "Static-to-Dynamic Error Comparison",
  "Strain Accumulation Forecast",
  "Stress-Barrier Decomposition",
  "Stress-Path Reassignment",
  "Structural Interference Mapping",
  "Structural Load Redistribution",
  "Subtractive Logic Filter",
  "Sudden-Shift Detection Ladder",
  "Symmetry-Break Prediction",
  "Systemic Drift Projection",
  "System-Overload Map",
  "Temporal Bottleneck Locator",
  "Temporal Causation Ladder",
  "Temporal Drift Reversal",
  "Temporal Friction Model",
  "Tension-Propagation Web",
  "Threshold-Before-Failure Scan",
  "Threshold Narrowing Indicator",
  "Time-Sensitivity Mapping",
  "Torque-Point Identification",
  "Translation-Error Forecast",
  "Transition-Friction Detection",
  "Trigger-Sensitivity Index",
  "Turbulence-Before-Break Test",
  "Unaccounted-Factor Isolation",
  "Unbalanced Load Checker",
  "Uncertainty Compression Grid",
  "Variance-Collapse Ladder",
  "Variance-to-Instability Ratio",
  "Velocity-of-Change Forecast",
  "Viscosity-of-Decision Map",
  "Weak-Signal Boosting Model",
  "Weight-Shift Influence Map",
  "Window-of-Intervention Detector",
  "Working-Backwards Constraint Cut",
  "Zero-Point Deviation Check",
  "Zero-Sum Conflict Mapping",
  "Zone-Shift Prediction",
  "Zone-of-Control Expansion",
  "Zone-Pressure Detector",
  "Z-Axis Drift Analysis",
  "Z-Pattern Transition Test",

  // Set 8 (200 New High-Power Frameworks)
  "Threshold-State Collapse Mapping",
  "Causal Ridge Detection",
  "Minimal Intervention Path",
  "Divergent Constraint Surfacing",
  "Structural Motif Extraction",
  "Entropy-Weighted Prioritization",
  "Boundary-Layer Diagnostic",
  "Failure-Mode Cross-Coupling",
  "Sequential Dominance Ladder",
  "Harmonic Pattern Resolution",
  "Cross-Domain Variable Substitution",
  "Constraint-Space Folding",
  "Fractal Causality Expansion",
  "Temporal Influence Weaving",
  "Elastic Constraint Deformation",
  "Control-Node Compression",
  "Central Gradient Detection",
  "Recursive Core Isolation",
  "Convergent Drift Mapping",
  "Multi-Node Perturbation Ranking",
  "Conflict Vector Decomposition",
  "Opposing-Force Reconciliation",
  "Micro-State Sensitivity Analysis",
  "Stability Ridge Projection",
  "Domino-Trajectory Mapping",
  "Hidden-State Signature Detection",
  "Process Skeleton Extraction",
  "Sequential Friction Ranking",
  "Edge-Case Collapse Test",
  "Double-Origin Comparison",
  "Multi-Lens Abstraction",
  "Heuristic Skeleton Mapping",
  "Invariant-Point Harvesting",
  "Disruption-Trigger Sorting",
  "Signal-to-Noise Pathfinding",
  "Causal Stream Narrowing",
  "Progressive Simplification Ladder",
  "Difference Amplifier Method",
  "Multi-Constraint Clash Finder",
  "Conditional Path Reversal",
  "Drift-to-Failure Projection",
  "Structural Hollow Detection",
  "Load-Bearing Assumption Test",
  "Interaction Pressure Index",
  "Entanglement Node Extraction",
  "System-Heat Mapping",
  "Constraint-Cycle Breaking",
  "Pattern-Thinning Technique",
  "Cascade Prediction Model",
  "Minimal-Proof Generator",
  "Variable-Switch Method",
  "Tri-Constraint Intersection",
  "Rotational Perspective Method",
  "Diagonal Reasoning Shift",
  "Convergent Fault Spine",
  "Stability-Envelope Mapping",
  "Intensity-Weighted Causality",
  "Deep-Layer Knot Identification",
  "Phase-Shift Logic",
  "Local-Maximum Disruption",
  "Reverse-Gradient Probing",
  "Structural Drift Identification",
  "Recursive Parity Checking",
  "Weak-Point Probability Ladder",
  "Interlock Mapping",
  "Propagation Path Diagramming",
  "Model-Compression Sweep",
  "Temporal Pinch-Point Detector",
  "Variance-Driven Error Surfacing",
  "Multi-Layer Signal Contrast",
  "Overlap-Signature Comparison",
  "Blind-Spot Extraction",
  "Constraint-Neutral Zone Finding",
  "Reverse-Trigger Identification",
  "Dynamic Range Limitation Test",
  "Stress-Test Cascade Mapping",
  "Perturb-and-Observe Logic",
  "Structural Inflection Point Analysis",
  "Recursive Boundary Testing",
  "Mutation-Path Generator",
  "Cross-Model Alignment",
  "Abstraction Ladder Switching",
  "Conflict-Origin Stripdown",
  "Component-Pressure Ranking",
  "Hard-Limit Detection",
  "Precise-Constraint Narrowing",
  "Indirect Evidence Triangulation",
  "Fault-Intensity Signature",
  "Divergence-Probability Mapping",
  "Cross-Level Structural Overlay",
  "Rotating Constraint Cube",
  "Layer-by-Layer Dismantling",
  "Prediction-Error Surfacing",
  "Recursive Outcome Filtering",
  "Structural Decoupling Sequence",
  "Influence-Radius Mapping",
  "Endpoint Reverse-Scanning",
  "Stress-Pair Decomposition",
  "Central-Mechanism Hypothesis",
  "Nonlinear Pinch-Point Test",
  "Multi-Trajectory Comparison",
  "Simplest-Explanation Extraction",
  "Error-Clustering Diagram",
  "Blind-Route Identification",
  "Shape-of-Failure Mapping",
  "Network-Density Interpretation",
  "Transition-Friction Sorting",
  "Root-Distance Estimation",
  "Resonance-Point Isolation",
  "Structural Interference Test",
  "Drift-Corrected Causality",
  "Misalignment Vector Analysis",
  "Localized Saturation Mapping",
  "Transition-Block Detection",
  "Threshold-Pressure Ranking",
  "Idea-Field Collapsing",
  "Layered Fault Partitioning",
  "Hybrid-Logic Weaving",
  "System-Skin Removal Technique",
  "Repeated-Pattern Verification",
  "Opposing-Hypothesis Duel",
  "Minimal-Energy Pathfinding",
  "Multi-Trigger Collapse Test",
  "Friction-Density Mapping",
  "Sequential Neutralization",
  "Compression-Point Isolation",
  "Missing-Link Detection",
  "Equivalent-Structure Substitution",
  "Data-Shape Inference",
  "Causal Shadow Analysis",
  "Repetition-Break Mapping",
  "Multi-Scale Fault Detection",
  "Translation-Layer Mapping",
  "Drift-Angle Measurement",
  "Assumption-Weight Index",
  "Deep-Layer Substitution",
  "Priority-Collapse Mapping",
  "Error-Rate Gradient",
  "Influence-Chain Shortening",
  "Small-World Constraint Mapping",
  "Order-Break Detection",
  "Autonomous Variable Ladder",
  "Pattern-Boundary Comparison",
  "Nonlinear Grid Extraction",
  "Two-State Conflict Mapping",
  "Interference-Origin Identification",
  "Sub-Threshold State Mapping",
  "Backward-Ripple Analysis",
  "Fault-Momentum Measurement",
  "Structural Resonance Mapping",
  "Pressure-Curve Inflection Detection",
  "Predictive Drift Propagation",
  "High-Impact Variable Sorting",
  "Opposing-Constraint Grid",
  "Outcome-Cluster Mapping",
  "Information-Loss Detection",
  "Multi-Path Collapse Prediction",
  "Nonlinear Interlock Diagnostic",
  "Depth-Layer Tension Mapping",
  "Transitional Energy Ranking",
  "Sharp-Edge Fault Mapping",
  "Boundary-Transition Analysis",
  "Recursive State-Space Reduction",
  "Phase-Barrier Identification",
  "Local-Cause Sorting",
  "Multi-Cause Intersection Detection",
  "Error-Shadow Overlay",
  "Structural Hardening Sequence",
  "Pivot-Mechanism Discovery",
  "Multi-Outcome Divergence Test",
  "Hidden-Layer Simplification",
  "Fault-Trajectory Drift",
  "Variable-Entanglement Index",
  "Cross-Phase Conflict Mapping",
  "Nonlinear Simplification Pass",
  "Collapse-Origin Extraction",
  "Convergent-State Discovery",
  "Divergent-State Prediction",
  "Dominant-Mechanism Projection",
  "Multi-Frame Causal Overlay",
  "Pre-Failure State Identification",
  "Minimal-Surface Logic",
  "Slow-Burn Fault Mapping",
  "Structural Saturation Detection",
  "System-Load Vectorization",
  "Fault-Envelope Projection",
  "Collapse-Pattern Extrapolation",
  "Multi-Cause Compression",
  "Differential-Impact Mapping",
  "Pivot-State Narrowing",
  "High-Noise Fault Finder",
  "Mechanism-Switch Analysis",
  "Rebound-Cause Identification",
  "Path-Criticality Index",
  "State-Transition Tightening",
  "Hybrid-Gradient Fault Detection",
  "Sequential Pruning Logic",
  "Non-Obvious Origin Mapping",
  "State-Collapse Grid",
  "Emergent Constraint Spotlighting",

  // Engines
  "Four-Pillar Information Control Engine"
];

// Deduplicating and cleaning the list
export const UNIQUE_FRAMEWORKS = Array.from(new Set(FRAMEWORKS)).sort();